### ISSUE TITLE
Rock Antelope

### ISSUE THREAD

**Issue by Paspartout** [UntitledAuthors/UntitledCreatureMod#4]
Implement the Rock Antelope.

### Stats

Name: Rock Antelope
Type:  None
Dimension/Biome:  Overworld/Savannah Plateau
Spawning time:  Day
Behaviour:  Normal - Passive
Leader - Neutral
HP: Normal - 5 Hearts
Leader - 8 Hearts
Attack types:  Melee ( High Knockback )
Attack strength:  1.5 hearts on Easy, 3 hearts on normal, 4 hearts on hard
Hitbox size:  Height - 1.8, Width - 0.9, Length - 1.8
Drops:  1 - 4 exp orbs, 0-3 Leather, 1-4 Meat, 0-1 Horns
Tamable:  No

### Rock Antelope Features/Todo:

- [x] Has a 75% reduced fall damage
- [x] Herd dynamic, there is a "leader" antelope and all the others will focus on being in an at-least 20 block radius of it
- [ ] They are quite shy and when approached they will run away, but if any are hit the leader will fight back
- [x] Headbutting competitions can happen between antelopes, during these little fights between antelopes they will headbutt each-other and there is a chance that they can - break one of their horns which the item of the horn itself will be dropped on the ground and the antelope that lost the headbutt will lose a horn on its model.
  - [ ] Align antelopes properly in distance and rotation before playing animation
  - [ ] Fix horn breaking at the wrong location
- [x] Don't render horns on babies
- [x] Don't render horn after jousting?
- [x] Make the horns on the leader antelope biggger
- [x] Will eat grass like sheep
- [x] Horn can be used to make a fancy banner pattern
  - [ ] Pattern currently too gray/washed out compared to vanilla ones
  - [ ] Need shield pattern 
- [X] Horn can be used to make a dagger
- [x] Horn can be used to make a war horn
- [x] Breedable with acacia leaves

**Comment by VakyPanda** [comment]
Pushed back this a couple of updates, will leave the issue so it can be reopened later but im closing it for now.
