### ISSUE TITLE
Mod Weapons

### ISSUE THREAD

**Issue by KThompson-Lane** [UntitledAuthors/UntitledCreatureMod#5]
Implementing the different weapons for the mod:

#### description:
A dagger made using an antelope horn which gives a unique bonus to those who dual wield the vicious weapon.
#### durability:
100

#### Damage:
5
#### Attack speed:
1.7, 1.9 when dual wielding 

#### Recipe:
1 bone and 1 Antelope horn in a diagonal pattern

### To do:

- [x] -Implement the item tier for Stonehorn item(s?)
- [x] -Register the stonehorn dagger item
- [ ] -Implement the dual wielding mechanic
- [ ] -Implement reach reduction

**Comment by KThompson-Lane** [comment]
## Rock Antelope Warhorn:
### Info:
#### description:
A warhorn made using a rock antelope horn which gives a strength buff to the player who uses it.
#### durability:
100

#### Damage:
N/A
#### Attack speed:
N/A Has a 20 second cooldown

#### Recipe:
TBD

### To do:

- [ ] -Implement the base item and model
- [ ] -Register the item
- [ ] -Implement the blowing mechanic

**Comment by VakyPanda** [comment]
### Life vest
- [ ] Add Life Vest Item
  - [ ] When worn will make the player float to the surface of water
  - [ ] Emits bubbles when in use inside water
  - Pull towards the surface is moderately fast
  -  Used to help drowning players
  - [ ] Will nullify the pull of magma blocks
  - [ ] Can be crafted with 6 hercules frog leather and 2 string like this
x = frog skin
y = air
z = string
x y x 
x z x
x z x

**Comment by Paspartout** [comment]
No please don't, we already got them in #7
I think we should make issues for creatures only not for every item
